### ISSUE TITLE
malformed response on get household information

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-AndroidClient#4]
Caught at callback stage, no idea what is being passed back.

**Comment by gsczechowski** [comment]
Getting a 400 error back: Number Format Execption

<h1>400 Bad Request</h1>NumberFormatException thrown

**Comment by bradwarrum** [comment]
A householdID of -1 is being passed into the getHouseholdInfo() call.  This is causing the problem.  I'll update the server because I think it's returning the error in the wrong format for URL parse errors, but on the client side the householdID passed in needs to be valid.

**Comment by gsczechowski** [comment]
Fixed. It was an int/long conversion issue
